version: '3'
services:
  rest_server:
    container_name: rest_server
    image: restic/rest-server
    volumes:
      - './data:/data'
    expose:
      - "80"
  ts-restic-proxy:
    image: ts-restic-proxy
    environment:
      RESTIC_SERVER_URL: http://rest_server:80
      TAILSCALE_AUTH_KEY: a8498d0dcc0aa46cf5cc7553780579ddb8d46f933b380837
      TAILSCALE_CONTROL_SERVER: https://headscale.jonaenz.de
      TAILSCALE_HOSTNAME: restic-server
      
    volumes:
      - "./proxy-data:/data"
      - type: bind
        source: ./data/.htpasswd
        target: /.htpasswd
    ports:
      - "8000:8000"
